spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 42306392438-kh2tg87ofkth437jvkhtjk13l6h2ta2k.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile